name = "record-collection"
pages_build_output_dir = "./dist"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "record-collection-db"
database_id = "71e620bf-1115-4594-8a78-5479b533cb07"

[[kv_namespaces]]
binding = "SYNC_KV"
id = "0b8cde34483545378dc864eae8b52b21"

[[kv_namespaces]]
binding = "SESSION"
id = "da7327b206914b2a8b45da2f9f7355e9"

[vars]
DISCOGS_USERNAME = "nkinds"
